import type { ProgramPageRow } from "./programTypes";

export const PROGRAM_PAGE_MATRIX = [
  {
    id: "home",
    group: "COMMAND",
    page: "Home",
    purpose: "전체 연구 상태와 안전 경계",
    delivery: "BUILT",
    evidenceState: "ETF_Q0_Q2_BLOCKED_Q1_Q2A",
    progress: 100,
    priority: "P1",
    nextAction: "point-in-time ETF 데이터 custody 확보",
    eta: "Q1 1~2일",
    mergeGate: "18점·44 준비도·Q3 잠금 분리",
  },
  {
    id: "scorecard",
    group: "COMMAND",
    page: "Program Scorecard",
    purpose: "점수와 페이지 감사",
    delivery: "BUILT",
    evidenceState: "MODEL_18_ETF_READINESS_44_PLATFORM_90",
    progress: 100,
    priority: "P1",
    nextAction: "ETF Q1·Q2-A·Q2-B gate 분리 추적",
    eta: "완료",
    mergeGate: "모델·플랫폼·lane 준비도 점수 분리",
  },
  {
    id: "rl-discovery",
    group: "RL",
    page: "Discovery Lab",
    purpose: "D0~D7 질문과 arm 균형성",
    delivery: "BUILT",
    evidenceState: "ETF_Q0_DONE_Q1_BLOCKED_Q2A_NO_GO_Q2B_PASS",
    progress: 100,
    priority: "P0",
    nextAction: "Q1 custody 보강 후 동일 prereg 재실행",
    eta: "Q1 1~2일",
    mergeGate: "기존 D7 NOT_RUN_NO_READ 유지",
  },
  {
    id: "rl-data",
    group: "RL",
    page: "Data",
    purpose: "split·비용·Fresh OOS 경계",
    delivery: "BUILT",
    evidenceState: "ETF_Q1_BLOCKED_FOUR_CUSTODY_GATES",
    progress: 100,
    priority: "P0",
    nextAction: "PIT universe·official identity·available_at·total return 확보",
    eta: "1~2일+데이터 확보",
    mergeGate: "bfill 0·mode=ro·leading-zero 유지",
  },
  {
    id: "rl-experiment",
    group: "RL",
    page: "Experiment",
    purpose: "가설·arm·seed·gate 사전등록",
    delivery: "BUILT",
    evidenceState: "ETF_Q0_PREREG_EXECUTED_Q2A_Q2B_RUN",
    progress: 100,
    priority: "P0",
    nextAction: "20일 momentum 외 새 가설은 별도 amendment",
    eta: "재가설 4~8시간",
    mergeGate: "5-fold·3-shuffle·9/23bp 기준 불변",
  },
  {
    id: "rl-training",
    group: "RL",
    page: "Training",
    purpose: "학습·모델·resume 상태",
    delivery: "BUILT",
    evidenceState: "ETF_Q3_LOCKED_NOT_RUN",
    progress: 100,
    priority: "P1",
    nextAction: "Q1·Q2-A 통과 전 PPO 모델 생성 금지",
    eta: "최소 3~5 작업일",
    mergeGate: "Residual MLP first·PPO not run",
  },
  {
    id: "rl-evaluation",
    group: "RL",
    page: "Evaluation",
    purpose: "비용·상한·negative control",
    delivery: "BUILT",
    evidenceState: "ETF_Q2A_23BP_NO_GO_1_OF_5",
    progress: 100,
    priority: "P0",
    nextAction: "공식 universe에서 supervised floor 재검증",
    eta: "Q1 후 1~2일",
    mergeGate: "native -9.23bp·DD 94.79%·1/5 공개",
  },
  {
    id: "rl-compare",
    group: "RL",
    page: "Compare",
    purpose: "알고리즘·control 비교",
    delivery: "BUILT",
    evidenceState: "ETF_NATIVE_MINUS_SHUFFLE_NEG_2_334BP",
    progress: 100,
    priority: "P1",
    nextAction: "23bp primary와 9bp diagnostic 동시 비교",
    eta: "완료",
    mergeGate: "9bp +4.77bp를 승격 근거로 사용 금지",
  },
  {
    id: "rl-report",
    group: "RL",
    page: "Report",
    purpose: "판정·artifact·거버넌스",
    delivery: "BUILT",
    evidenceState: "ETF_Q0_Q2_RECEIPT_5547B737",
    progress: 100,
    priority: "P1",
    nextAction: "실행 브랜치→부모 연구 브랜치 PR",
    eta: "완료",
    mergeGate: "receipt SHA·BLOCKED·NO-GO·PASS 동시 보존",
  },
  {
    id: "insights",
    group: "RESEARCH",
    page: "Insights",
    purpose: "종목·수급·시장 구간 관찰",
    delivery: "BUILT",
    evidenceState: "ETF_CANARY_DIAGNOSTIC_ONLY",
    progress: 76,
    priority: "P2",
    nextAction: "마지막 fold 양수 원인을 사후 주장 없이 관찰",
    eta: "30~60분",
    mergeGate: "4-code canary를 alpha로 주장 금지",
  },
  {
    id: "lanes",
    group: "PLATFORM",
    page: "Other Lanes",
    purpose: "인트라데이·외부 설계 보조 연구",
    delivery: "BUILT",
    evidenceState: "EXTERNAL_DESIGN_REFERENCE_ONLY",
    progress: 73,
    priority: "P2",
    nextAction: "외부 설계와 RL 성과 분리 유지",
    eta: "30분",
    mergeGate: "RL 성과 합산 금지",
  },
  {
    id: "kronos",
    group: "PLATFORM",
    page: "Kronos",
    purpose: "시계열 예측 모델 가용성과 RL 정책의 역할 분리",
    delivery: "BUILT",
    evidenceState: "AVAILABLE_NOT_LOADED_NOT_RL_POLICY",
    progress: 82,
    priority: "P1",
    nextAction: "예측값을 PIT feature로 사용할 별도 가설 사전등록",
    eta: "가설 4~8시간·검증 1~2일",
    mergeGate: "Kronos 예측을 RL 수익으로 오인 금지",
  },
  {
    id: "settings",
    group: "ADVANCED",
    page: "Settings",
    purpose: "테마·화면·로컬 연구 환경",
    delivery: "BUILT",
    evidenceState: "ETF_DB_READ_ONLY_Q3_EXECUTION_DISABLED",
    progress: 84,
    priority: "HOLD",
    nextAction: "artifact root와 데이터 cutoff만 읽기 전용 표시",
    eta: "15분",
    mergeGate: "학습·브로커·계좌 제어 없음",
  },
] as const satisfies readonly ProgramPageRow[];
