import type { ProgramPageRow } from "./programTypes";

export const PROGRAM_PAGE_MATRIX = [
  {
    id: "home",
    group: "COMMAND",
    page: "Home",
    purpose: "전체 연구 상태와 안전 경계",
    delivery: "BUILT",
    evidenceState: "D6R_TRAIN_NO_GO_VISIBLE",
    progress: 100,
    priority: "P1",
    nextAction: "D6R2 MDP 재설계 연결",
    eta: "완료",
    mergeGate: "판정·증거 일치",
  },
  {
    id: "scorecard",
    group: "COMMAND",
    page: "Program Scorecard",
    purpose: "점수와 페이지 감사",
    delivery: "BUILT",
    evidenceState: "D6R_AUDITED_83",
    progress: 100,
    priority: "P1",
    nextAction: "D6R2 상태 추적",
    eta: "완료",
    mergeGate: "가중치 100%",
  },
  {
    id: "rl-discovery",
    group: "RL",
    page: "Discovery Lab",
    purpose: "D0~D7 질문과 arm 균형성",
    delivery: "BUILT",
    evidenceState: "D6R_PRIMARY_60_OF_60_NO_GO",
    progress: 100,
    priority: "P0",
    nextAction: "gamma=0/contextual 대 stateful MDP 반증",
    eta: "완료",
    mergeGate: "60/60+receipt+control",
  },
  {
    id: "rl-data",
    group: "RL",
    page: "Data",
    purpose: "split·비용·Fresh OOS 경계",
    delivery: "BUILT",
    evidenceState: "D6R_TRAIN_573_FIVE_FOLDS",
    progress: 100,
    priority: "P0",
    nextAction: "새 확인 기간 봉인 유지",
    eta: "완료",
    mergeGate: "input SHA·read count 고정",
  },
  {
    id: "rl-experiment",
    group: "RL",
    page: "Experiment",
    purpose: "가설·arm·seed·gate 사전등록",
    delivery: "BUILT",
    evidenceState: "D6R_PREREG_EXECUTED",
    progress: 100,
    priority: "P0",
    nextAction: "D6R2 preregistration",
    eta: "2~4시간",
    mergeGate: "fold-local scaler·train-only 입력",
  },
  {
    id: "rl-training",
    group: "RL",
    page: "Training",
    purpose: "학습·모델·resume 상태",
    delivery: "BUILT",
    evidenceState: "D6R_PRIMARY_60_MODELS_3M_STEPS",
    progress: 100,
    priority: "P1",
    nextAction: "D6R 모델 동결; 동일 penalty 재튜닝 금지",
    eta: "완료",
    mergeGate: "60 모델·3M steps hash 보존",
  },
  {
    id: "rl-evaluation",
    group: "RL",
    page: "Evaluation",
    purpose: "비용·상한·negative control",
    delivery: "BUILT",
    evidenceState: "D6R_TRAIN_FALSIFICATION_NOT_CONFIRMED",
    progress: 100,
    priority: "P0",
    nextAction: "MDP 오지정 가설을 train-only에서 반증",
    eta: "완료",
    mergeGate: "1/10 gate·D7 봉인",
  },
  {
    id: "rl-compare",
    group: "RL",
    page: "Compare",
    purpose: "알고리즘·control 비교",
    delivery: "BUILT",
    evidenceState: "D6R_NATIVE_DELTA_POS_0_017_BELOW_GATE",
    progress: 100,
    priority: "P1",
    nextAction: "gamma=0 DQN·bandit·supervised ceiling 비교",
    eta: "완료",
    mergeGate: "control 분리 유지",
  },
  {
    id: "rl-report",
    group: "RL",
    page: "Report",
    purpose: "판정·artifact·거버넌스",
    delivery: "BUILT",
    evidenceState: "D6R_RECEIPT_CUSTODY",
    progress: 100,
    priority: "P1",
    nextAction: "PR·merge·tag 계보 연결",
    eta: "완료",
    mergeGate: "SHA·60 outcomes·NO-GO",
  },
  {
    id: "insights",
    group: "RESEARCH",
    page: "Insights",
    purpose: "종목·수급·시장 구간 관찰",
    delivery: "BUILT",
    evidenceState: "OBSERVATION_ONLY",
    progress: 76,
    priority: "P2",
    nextAction: "검증 입력 경계 강화",
    eta: "30~60분",
    mergeGate: "alpha 주장 없음",
  },
  {
    id: "lanes",
    group: "PLATFORM",
    page: "Other Lanes",
    purpose: "인트라데이·Kronos 보조 연구",
    delivery: "BUILT",
    evidenceState: "INELIGIBLE_FOR_RL_RANK",
    progress: 73,
    priority: "P2",
    nextAction: "RL 점수 제외 유지",
    eta: "30분",
    mergeGate: "RL 성과 합산 금지",
  },
  {
    id: "settings",
    group: "ADVANCED",
    page: "Settings",
    purpose: "테마·화면·로컬 연구 환경",
    delivery: "BUILT",
    evidenceState: "LOCAL_ONLY",
    progress: 84,
    priority: "HOLD",
    nextAction: "실행 권한 추가 보류",
    eta: "15분",
    mergeGate: "읽기 전용 경계",
  },
] as const satisfies readonly ProgramPageRow[];
