import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { V6_PAGES } from '../registry';
import { PROGRAM_EXECUTION } from './programExecution';
import { PROGRAM_LANES, PROGRAM_PAGE_MATRIX, programOverallScore } from './programScorecard';

const researchContext = readFileSync(new URL('../ResearchContext.svelte', import.meta.url), 'utf8');
const executionStrip = readFileSync(new URL('../ProgramExecutionStrip.svelte', import.meta.url), 'utf8');
const scorecardPage = readFileSync(new URL('../pages/ProgramScorecardPage.svelte', import.meta.url), 'utf8');

test('execution banner preserves current daily-close research boundary and lineage', () => {
  assert.equal(PROGRAM_EXECUTION.overallScore, programOverallScore(PROGRAM_LANES));
  assert.equal(PROGRAM_EXECUTION.overallScore, 71);
  assert.equal(PROGRAM_EXECUTION.implementationScore, 94);
  assert.equal(PROGRAM_EXECUTION.economicModelScore, 20);
  assert.equal(PROGRAM_EXECUTION.liveReadinessScore, 0);
  assert.equal(PROGRAM_EXECUTION.pageCount, V6_PAGES.length);
  assert.equal(PROGRAM_EXECUTION.freshOos, 'NOT_RUN_NO_READ');
  assert.equal(PROGRAM_EXECUTION.liveTrading, 'BLOCKED');
  assert.match(PROGRAM_EXECUTION.deliveryLane, /codex\/v1.29.0-dev-<task>/);
  assert.match(PROGRAM_EXECUTION.deliveryLane, /develop\/v1.29.0-dev/);
  assert.match(PROGRAM_EXECUTION.deliveryLane, /v1.28.0/);
  assert.equal(PROGRAM_EXECUTION.developmentVersion, 'v1.29.0-dev');
  assert.equal(PROGRAM_EXECUTION.latestRelease, 'v1.28.0');
  assert.equal(PROGRAM_EXECUTION.versionPolicy, 'ONE_DEV_LINE_TASK_BRANCH_NO_FF_PRESERVE');
  assert.equal(PROGRAM_EXECUTION.branchRetentionPolicy, 'KEEP_MERGED_BRANCHES');
  assert.match(PROGRAM_EXECUTION.deliveryLane, /MERGED 보존/);
  assert.equal(PROGRAM_EXECUTION.stage, 'V1_29_DEV_CUSTODY_REPRODUCTION_AUTHORITY_BLOCKED');
  assert.equal(PROGRAM_EXECUTION.authority, 'BOUND_LOCAL_AUDIT_BLOCKED');
  assert.equal(PROGRAM_EXECUTION.reviewedRun, 'DAILY_MARKET_ALLOCATION_SCREEN_2026_08_10_002');
  assert.match(PROGRAM_EXECUTION.nextAction, /reviewer trust root/);
  assert.match(PROGRAM_EXECUTION.nextAction, /extraction receipt/);
  assert.match(PROGRAM_EXECUTION.nextAction, /20~60거래일/);
  assert.match(PROGRAM_EXECUTION.eta, /표본 축적 4~12주/);
  assert.match(PROGRAM_EXECUTION.eta, /판정 실행 2~4시간/);
  assert.equal(PROGRAM_PAGE_MATRIX.find((page) => page.id === 'rl-evaluation')?.eta, '표본 축적 4~12주 + 판정 2~4시간');
  assert.ok(PROGRAM_PAGE_MATRIX.some((page) => page.id === 'kronos'));
  assert.match(researchContext, /D0\/D1 · A1/);
  assert.match(researchContext, /TRAIN 76 · VAL 24 · TEST FEATURES CONSUMED/);
  assert.match(researchContext, /이전 20 NO-GO · 신규 10 VAL/);
  assert.match(researchContext, /historical TEST 중앙값 -10\.19%/);
  assert.match(researchContext, /2,432 TRANSITIONS/);
  assert.match(researchContext, /NOT_RUN_NO_READ/);
  assert.match(executionStrip, /PROGRAM_EXECUTION\.developmentVersion/);
  assert.match(scorecardPage, /병합된 작업 브랜치는 MERGED 이력으로 보존합니다/);
  assert.match(scorecardPage, /다음 개발선은 develop\/v1.29.0-dev/);
  assert.match(scorecardPage, /모델 GO를 뜻하지 않습니다/);
  assert.match(scorecardPage, /V6_PAGES/u);
  assert.match(scorecardPage, /V6_PAGES\.length/u);
  assert.match(scorecardPage, /기능·워크플로 단계/u);
  assert.match(scorecardPage, /capabilityLabel\(item\.id, item\.capability\)/u);
  assert.doesNotMatch(scorecardPage, /13개 페이지/u);
  assert.doesNotMatch(scorecardPage, /작업 브랜치는 삭제합니다/);
});
