import type { ProgramCapability, ProgramPageRow } from "./programTypes";

export const PROGRAM_PAGE_MATRIX = [
  {
    id: "home",
    group: "COMMAND",
    page: "Home",
    purpose: "전체 연구 상태와 안전 경계",
    delivery: "BUILT",
    evidenceState: "D6_VALIDATION_NO_GO_VISIBLE",
    progress: 100,
    priority: "P1",
    nextAction: "D6R 계획 연결",
    eta: "완료",
    mergeGate: "판정·증거 일치",
  },
  {
    id: "scorecard",
    group: "COMMAND",
    page: "Program Scorecard",
    purpose: "점수와 페이지 감사",
    delivery: "BUILT",
    evidenceState: "D6_AUDITED_82",
    progress: 100,
    priority: "P1",
    nextAction: "D6R 상태 추적",
    eta: "완료",
    mergeGate: "가중치 100%",
  },
  {
    id: "rl-discovery",
    group: "RL",
    page: "Discovery Lab",
    purpose: "D0~D7 질문과 arm 균형성",
    delivery: "BUILT",
    evidenceState: "D6_PRIMARY_6_OF_6_NO_GO",
    progress: 100,
    priority: "P0",
    nextAction: "D6R train-only falsification",
    eta: "완료",
    mergeGate: "6/6+receipt+control",
  },
  {
    id: "rl-data",
    group: "RL",
    page: "Data",
    purpose: "split·비용·Fresh OOS 경계",
    delivery: "BUILT",
    evidenceState: "D6_VALIDATION_128_BOUND",
    progress: 100,
    priority: "P0",
    nextAction: "새 확인 기간 봉인 유지",
    eta: "완료",
    mergeGate: "input SHA·read count 고정",
  },
  {
    id: "rl-experiment",
    group: "RL",
    page: "Experiment",
    purpose: "가설·arm·seed·gate 사전등록",
    delivery: "BUILT",
    evidenceState: "D6_PREREG_EXECUTED",
    progress: 100,
    priority: "P0",
    nextAction: "D6R preregistration",
    eta: "1~2시간",
    mergeGate: "train-only 입력만 사용",
  },
  {
    id: "rl-training",
    group: "RL",
    page: "Training",
    purpose: "학습·모델·resume 상태",
    delivery: "BUILT",
    evidenceState: "D5S_PRIMARY_36_OF_36",
    progress: 100,
    priority: "P1",
    nextAction: "D5S 모델 동결; validation 재튜닝 금지",
    eta: "완료",
    mergeGate: "모델 hash 보존",
  },
  {
    id: "rl-evaluation",
    group: "RL",
    page: "Evaluation",
    purpose: "비용·상한·negative control",
    delivery: "BUILT",
    evidenceState: "D6_REUSED_VALIDATION_NOT_CONFIRMED",
    progress: 100,
    priority: "P0",
    nextAction: "새 가설은 train-only에서 반증",
    eta: "완료",
    mergeGate: "1/7 gate·D7 봉인",
  },
  {
    id: "rl-compare",
    group: "RL",
    page: "Compare",
    purpose: "알고리즘·control 비교",
    delivery: "BUILT",
    evidenceState: "D6_NATIVE_DELTA_NEG_0_039",
    progress: 100,
    priority: "P1",
    nextAction: "D5S train과 D6 validation 격차 추적",
    eta: "완료",
    mergeGate: "control 분리 유지",
  },
  {
    id: "rl-report",
    group: "RL",
    page: "Report",
    purpose: "판정·artifact·거버넌스",
    delivery: "BUILT",
    evidenceState: "D6_RECEIPT_CUSTODY",
    progress: 100,
    priority: "P1",
    nextAction: "PR·merge·tag 계보 연결",
    eta: "완료",
    mergeGate: "SHA·6 outcomes·NO-GO",
  },
  {
    id: "insights",
    group: "RESEARCH",
    page: "Insights",
    purpose: "종목·수급·시장 구간 관찰",
    delivery: "BUILT",
    evidenceState: "OBSERVATION_ONLY",
    progress: 76,
    priority: "P2",
    nextAction: "검증 입력 경계 강화",
    eta: "30~60분",
    mergeGate: "alpha 주장 없음",
  },
  {
    id: "lanes",
    group: "PLATFORM",
    page: "Other Lanes",
    purpose: "인트라데이·Kronos 보조 연구",
    delivery: "BUILT",
    evidenceState: "INELIGIBLE_FOR_RL_RANK",
    progress: 73,
    priority: "P2",
    nextAction: "RL 점수 제외 유지",
    eta: "30분",
    mergeGate: "RL 성과 합산 금지",
  },
  {
    id: "settings",
    group: "ADVANCED",
    page: "Settings",
    purpose: "테마·화면·로컬 연구 환경",
    delivery: "BUILT",
    evidenceState: "LOCAL_ONLY",
    progress: 84,
    priority: "HOLD",
    nextAction: "실행 권한 추가 보류",
    eta: "15분",
    mergeGate: "읽기 전용 경계",
  },
] as const satisfies readonly ProgramPageRow[];

export const PROGRAM_CAPABILITIES = [
  {
    id: "d0-d3-history",
    capability: "D0~D3 검증 증거 조회",
    state: "AVAILABLE",
    boundary: "기존 판정은 변경하지 않음",
  },
  {
    id: "d4-primary",
    capability: "D4 4-algorithm × 2-reward × 3-seed",
    state: "AVAILABLE",
    boundary: "DQN train-only 확인; 수익성 근거 아님",
  },
  {
    id: "d5-primary",
    capability: "D5 DQN × 2-reward × 5-seed · 23bp",
    state: "AVAILABLE",
    boundary: "10개 실제 RL 모델; full-train gate NOT_CONFIRMED",
  },
  {
    id: "d5r-primary",
    capability: "D5R DQN × 2-reward × 3-seed × 2-checkpoint",
    state: "AVAILABLE",
    boundary: "capacity gate NOT_CONFIRMED",
  },
  {
    id: "d5s-primary",
    capability: "D5S DQN × 2-reward × 3-seed × 6-checkpoint",
    state: "AVAILABLE",
    boundary: "100K TRAIN_ONLY stability CONFIRMED",
  },
  {
    id: "d6-validation",
    capability: "D6 reused validation × 2-reward × 3-seed",
    state: "AVAILABLE",
    boundary: "6 evaluations; validation NO-GO; D7 locked",
  },
  {
    id: "artifact-audit",
    capability: "prereg·receipt·custody 감사",
    state: "AVAILABLE",
    boundary: "로컬 연구 evidence",
  },
  {
    id: "d6r-research",
    capability: "D6R train-only falsification",
    state: "PARTIAL",
    boundary: "사전등록 후 시작 가능; validation 재사용 금지",
  },
  {
    id: "fresh-oos",
    capability: "D7 Fresh OOS 조회",
    state: "BLOCKED",
    boundary: "NOT_RUN_NO_READ",
  },
  {
    id: "live-trading",
    capability: "브로커 주문·라이브 운영",
    state: "BLOCKED",
    boundary: "권한·검증·운영 체계 없음",
  },
] as const satisfies readonly ProgramCapability[];
