<script lang="ts">
  import { onMount } from 'svelte';
  import { getV6RunDetail, getV6Runs, type V6RunDetail, type V6Runs, type V6RunSeed } from '../v6Api';
  const INITIAL_CAPITAL = 60000000;
  let runsData = $state<V6Runs | null>(null); let detail = $state<V6RunDetail | null>(null); let selected = $state(''); let error = $state<string | null>(null); let loading = $state(true); let detailLoading = $state(false);
  function runKey(dataset: string | undefined, train: string | undefined): string { return `${dataset ?? ''}\u0000${train ?? ''}`; } function text(value: unknown): string { return value === undefined || value === null || value === '' ? 'MISSING' : String(value); } function number(value: unknown): number | undefined { return typeof value === 'number' && Number.isFinite(value) ? value : undefined; } function won(value: unknown): string { const amount = number(value); return amount === undefined ? 'MISSING' : `₩${new Intl.NumberFormat('ko-KR').format(amount)}`; } function navReturn(nav: unknown): string { const value = number(nav); return value === undefined ? 'MISSING' : `${((value / INITIAL_CAPITAL - 1) * 100).toFixed(2)}%`; } function seeds(): readonly [string, V6RunSeed][] { return Object.entries(detail?.manifest?.per_seed ?? {}); } function baselineNav(name: string): number | undefined { return number(detail?.manifest?.baselines?.[name]?.nav); }
  async function load(): Promise<void> { loading = true; error = null; const result = await getV6Runs(); loading = false; if (result.ok && result.data) runsData = result.data; else error = result.error ?? '알 수 없는 오류가 발생했습니다.'; } async function selectRun(): Promise<void> { const [dataset, train] = selected.split('\u0000'); if (!dataset || !train) return; detailLoading = true; detail = null; error = null; const result = await getV6RunDetail(dataset, train); detailLoading = false; if (result.ok && result.data) detail = result.data; else error = result.error ?? '알 수 없는 오류가 발생했습니다.'; } onMount(load);
</script>
{#if loading}<section class="panel" aria-live="polite">비교할 실행 기록을 확인하고 있습니다.</section>{:else if error && !runsData}<section class="panel error"><h1>비교 실행 기록을 불러오지 못했습니다</h1><p>{error}</p><button onclick={load}>다시 시도</button></section>{:else if runsData}<section class="compare-page"><header><p class="eyebrow">RESEARCH COMPARISON</p><h1>비교</h1><p>같은 실행 manifest의 검증 결과만 비교합니다.</p></header>{#if !(runsData.runs?.length)}<section class="empty-state"><h2>비교할 실행이 없습니다</h2><p>학습 페이지에서 데이터셋과 학습 실행 기록을 먼저 확인하세요.</p></section>{:else}<section class="card"><h2>실행 선택</h2>{#each runsData.runs ?? [] as run}<button class:chosen={selected === runKey(run.dataset_run_id,run.run_id)} onclick={() => { selected=runKey(run.dataset_run_id,run.run_id); selectRun(); }}>{text(run.dataset_run_id)} · {text(run.run_id)} · {text(run.verdict_candidate?.value)}</button>{/each}</section>{#if detailLoading}<section class="card">선택한 실행 manifest를 읽고 있습니다.</section>{:else if error}<section class="card error">{error}</section>{:else if detail?.manifest}<section class="card"><h2>전략 비교</h2><div class="table-wrap"><table><thead><tr><th>지표</th>{#each seeds() as [seed]}<th>policy seed {seed}</th>{/each}<th>no_trade</th><th>rule_topk_ret5</th><th>random_topk</th><th>KOSPI / KOSDAQ</th></tr></thead><tbody><tr><th>val NAV</th>{#each seeds() as [,value]}<td>{won(value.final_val_metrics?.nav)}</td>{/each}<td>{won(baselineNav('no_trade'))}</td><td>{won(baselineNav('rule_topk_ret5'))}</td><td>{won(baselineNav('random_topk'))}</td><td rowspan="2" class="blocked">BLOCKED_INDEX_SERIES_SOURCE · KRX 자격증명 필요</td></tr><tr><th>return %</th>{#each seeds() as [,value]}<td>{navReturn(value.final_val_metrics?.nav)}</td>{/each}<td>{navReturn(baselineNav('no_trade'))}</td><td>{navReturn(baselineNav('rule_topk_ret5'))}</td><td>{navReturn(baselineNav('random_topk'))}</td></tr></tbody></table></div></section><section class="card"><h2>변형 검증</h2><p>H3 / H5 · NOT_RUN · 변형 검증 대기</p></section>{/if}{/if}</section>{/if}
<style>.compare-page,.panel{max-width:980px;border:1px solid var(--border);border-radius:14px;padding:clamp(18px,4vw,32px);background:var(--surface);color:var(--fg)}.eyebrow{color:var(--accent);font-size:.72rem;font-weight:800;letter-spacing:.1em}h1,h2{color:var(--fg-strong)}header>p{color:var(--muted)}.card,.empty-state{margin-top:16px;border:1px solid var(--border-strong);border-radius:10px;padding:16px;background:var(--surface-raised)}.empty-state{border-color:var(--warn);background:var(--warn-soft)}button{display:block;width:100%;margin:6px 0;border:1px solid var(--border-strong);border-radius:6px;padding:8px;background:var(--surface-sunken);color:var(--fg);font:inherit;text-align:left}.chosen{border-color:var(--accent)}.table-wrap{overflow-x:auto}table{width:100%;min-width:720px;border-collapse:collapse}th,td{border-top:1px solid var(--border);padding:7px;text-align:left}th{color:var(--muted)}.blocked,.error{color:var(--danger);background:var(--danger-soft)}</style>