<script lang="ts">
  import { onMount } from 'svelte';
  import { getV6Experiment, type V6Experiment } from '../v6Api';
  let experiment = $state<V6Experiment | null>(null); let error = $state<string | null>(null); let loading = $state(true);
  const text = (value: unknown) => value === undefined || value === null || value === '' ? 'MISSING' : typeof value === 'string' ? value : JSON.stringify(value);
  const won = (value: unknown) => typeof value === 'number' ? `₩${new Intl.NumberFormat('ko-KR').format(value)}` : 'MISSING';
  const lockState = (value: boolean | undefined) => value === false ? 'false' : value === true ? 'true' : 'MISSING';
  async function load(): Promise<void> { loading = true; error = null; const result = await getV6Experiment(); if (result.ok && result.data) experiment = result.data; else error = result.error ?? '실험 API를 불러오지 못했습니다.'; loading = false; }
  onMount(() => { void load(); });
</script>

<section class="experiment-page" aria-labelledby="experiment-title">
  <header><p class="eyebrow">EXPERIMENT CONTRACT</p><h1 id="experiment-title">실험 설계</h1><p>표시된 계약은 읽기 전용 API 응답에 한정됩니다. MISSING은 성공한 응답에 필드가 없는 경우입니다.</p></header>
  {#if loading}<p class="notice" role="status">실험 설계를 확인하고 있습니다.</p>{/if}
  {#if error}<section class="notice error" role="alert"><strong>UNAVAILABLE</strong><span>{error}</span><button type="button" onclick={() => void load()}>다시 시도</button></section>{/if}
  {#if experiment}<div class="grid stats"><section class="card"><p>자본</p><strong>{won(experiment.planned?.capital?.initial_krw)}</strong></section><section class="card"><p>슬롯</p><strong>{text(experiment.planned?.capital?.slots)} × {won(experiment.planned?.capital?.slot_budget_krw)}</strong></section><section class="card"><p>예비</p><strong>{won(experiment.planned?.capital?.reserve_krw)}</strong></section><section class="card"><p>전략</p><strong>{text(experiment.planned?.strategy)}</strong></section></div>
  <section class:ready={experiment.prereg?.state === 'FROZEN'} class="card prereg"><h2>사전등록 계보 <span class="chip">{text(experiment.prereg?.state)}</span></h2><dl><div><dt>identity/path</dt><dd>{text(experiment.prereg?.path)}</dd></div><div><dt>SHA-256</dt><dd>{text(experiment.prereg?.sha256)}</dd></div><div><dt>동결 시각</dt><dd>{text(experiment.prereg?.frozen_utc)}</dd></div><div><dt>가설</dt><dd>{text(experiment.prereg?.hypothesis)}</dd></div></dl><p>이 화면은 실행 명령을 제공하지 않으며, 표시값은 위 사전등록 SHA에 결속된 API 계약만 나타냅니다.</p></section>
  <div class="grid details"><section class="card"><h2>horizon·실행 기준</h2><dl><div><dt>primary horizon</dt><dd>{text(experiment.planned?.horizons?.primary)}</dd></div><div><dt>validation horizons</dt><dd>{text(experiment.planned?.horizons?.validation)}</dd></div><div><dt>price basis</dt><dd>{text(experiment.planned?.execution?.price_basis)}</dd></div><div><dt>official close</dt><dd>{text(experiment.planned?.execution?.official_close)}</dd></div></dl></section><section class="card"><h2>비용 계약</h2><dl><div><dt>primary</dt><dd>{text(experiment.planned?.costs?.primary)}</dd></div><div><dt>zero control</dt><dd>{text(experiment.planned?.costs?.zero_control)}</dd></div><div><dt>stress</dt><dd>{text(experiment.planned?.costs?.stress)}</dd></div></dl></section><section class="card"><h2>dataset·universe</h2><dl><div><dt>dataset contract</dt><dd>{text(experiment.planned?.dataset_contract)}</dd></div><div><dt>manifest</dt><dd>{text(experiment.planned?.universe?.manifest)}</dd></div><div><dt>universe size</dt><dd>{text(experiment.planned?.universe?.size)}</dd></div><div><dt>seeds</dt><dd>{text(experiment.planned?.seeds)}</dd></div></dl></section><section class="card"><h2>제약</h2><dl>{#each Object.entries(experiment.planned?.constraints ?? {}) as [constraint, value]}<div><dt>{constraint}</dt><dd>{text(value)}</dd></div>{:else}<div><dt>constraints</dt><dd>MISSING</dd></div>{/each}</dl></section></div>
  <section class="card locks"><h2>여섯 안전 잠금</h2><div class="lock-grid">{#each Object.entries(experiment.locks ?? {}) as [lock, value]}<div><span>{lock}</span><strong class:unsafe={value !== false}>{lockState(value)}</strong></div>{:else}<p>MISSING</p>{/each}</div><p>{Object.keys(experiment.locks ?? {}).length === 6 && Object.values(experiment.locks ?? {}).every((value) => value === false) ? '6/6 false · 모든 잠금은 false입니다.' : 'MISSING 또는 false 이외의 잠금이 있습니다.'}</p></section>
  {/if}
</section>

<style>
  .experiment-page { width:100%;min-width:0;border:1px solid var(--border);border-radius:14px;padding:clamp(18px,4vw,32px);background:var(--surface);color:var(--fg) }.grid { display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:16px;margin-top:16px }.card { min-width:0;border:1px solid var(--border-strong);border-radius:10px;padding:16px;background:var(--surface-raised) }.eyebrow { margin:0;color:var(--accent);font-size:.82rem;font-weight:800;letter-spacing:.1em }h1 { margin:7px 0;color:var(--fg-strong);font-size:clamp(1.8rem,6vw,2.6rem) }h2 { margin:0 0 12px;color:var(--fg-strong);font-size:1.15rem }.stats p,dt { margin:0;color:var(--muted) }.stats strong { display:block;margin-top:8px;color:var(--fg-strong);font-size:1.3rem;overflow-wrap:anywhere }.notice { margin-top:16px;padding:12px;border:1px solid var(--border-strong);border-radius:10px;color:var(--muted) }.error { display:flex;flex-wrap:wrap;gap:8px 12px;align-items:center;border-color:var(--danger);color:var(--danger) }.prereg,.locks { margin-top:16px }.ready { border-color:var(--success);background:var(--success-soft) }.chip { border:1px solid currentColor;border-radius:999px;padding:2px 6px;color:var(--warn);font-size:.78rem }.ready .chip { color:var(--success) }dl { margin:0;display:grid;gap:10px }dd { margin:3px 0 0;overflow-wrap:anywhere }.lock-grid { display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,180px),1fr));gap:8px }.lock-grid>div { display:flex;justify-content:space-between;gap:8px;border:1px solid var(--border);border-radius:6px;padding:8px;overflow-wrap:anywhere }.lock-grid strong { color:var(--success) }.lock-grid strong.unsafe { color:var(--danger) }button { border:1px solid var(--accent);border-radius:6px;padding:6px 10px;background:transparent;color:var(--accent-strong);font:inherit;cursor:pointer }button:focus-visible { outline:2px solid var(--accent);outline-offset:2px }
</style>
