<script lang="ts">
  import { onMount } from 'svelte'; import EChartsRenderer from '../../charts/EChartsRenderer.svelte'; import { getV6Experiment, type V6Experiment } from '../v6Api';
  const DATASET_COMMAND='py -3.11 -m stom_rl.daily_v6_dataset --universe-limit 500 --run-id v6_dataset_full_001'; const TRAIN_COMMAND='py -3.11 -m stom_rl.daily_v6_train --dataset v6_dataset_full_001 --seeds 0,1,2';
  let experiment=$state<V6Experiment|null>(null); let error=$state<string|null>(null); let loading=$state(true); let copyMessage=$state<string|null>(null);
  const text=(v:unknown)=>v===undefined||v===null||v===''?'MISSING':typeof v==='string'?v:JSON.stringify(v); const won=(v:unknown)=>typeof v==='number'?`₩${new Intl.NumberFormat('ko-KR').format(v)}`:'MISSING';
  const allocationOption=$derived({tooltip:{trigger:'axis'},xAxis:{type:'value',max:60000000,axisLabel:{formatter:(v:number)=>`₩${(v/1000000).toFixed(0)}M`}},yAxis:{type:'category',data:['자본 배분']},series:[{type:'bar',stack:'capital',name:'투자한도',data:[50000000],itemStyle:{color:'var(--accent)'}},{type:'bar',stack:'capital',name:'예비',data:[10000000],itemStyle:{color:'var(--warn)'}}]});
  async function load(){loading=true;error=null;const r=await getV6Experiment();loading=false;if(r.ok&&r.data)experiment=r.data;else error=r.error??'알 수 없는 오류가 발생했습니다.'} async function copy(command:string){try{await navigator.clipboard.writeText(command);copyMessage='명령을 클립보드에 복사했습니다.'}catch{copyMessage='클립보드를 사용할 수 없습니다. 아래 명령을 직접 복사하세요.'}} onMount(load);
</script>
{#if loading}<section class="panel">실험 설계를 확인하고 있습니다.</section>{:else if error}<section class="panel error"><h1>실험 설계를 불러오지 못했습니다</h1><p>{error}</p><button onclick={load}>다시 시도</button></section>{:else if experiment}<section class="experiment-page"><header><p class="eyebrow">EXPERIMENT CONTRACT</p><h1>실험 설계</h1><p>표시된 설계 계약은 읽기 전용 API 응답에서만 가져옵니다.</p></header>
<div class="grid stats"><section class="card"><p>자본</p><strong>{won(experiment.planned?.capital?.initial_krw)}</strong></section><section class="card"><p>슬롯</p><strong>{text(experiment.planned?.capital?.slots)} × {won(experiment.planned?.capital?.slot_budget_krw)}</strong></section><section class="card"><p>예비</p><strong>{won(experiment.planned?.capital?.reserve_krw)}</strong></section><section class="card"><p>비용</p><strong>{text(experiment.planned?.costs?.primary)}</strong></section></div>
<section class="card wide"><h2>자본 배분</h2><EChartsRenderer option={allocationOption} height="260px" caption="투자한도 50M · 예비 10M" /></section>
<section class:ready={experiment.prereg?.state==='FROZEN'} class="card prereg"><h2>사전등록 상태 <span class="chip">{text(experiment.prereg?.state)}</span></h2>{#if experiment.prereg?.state==='FROZEN'}<p>동결됨 · 사전등록 SHA-256이 확인되었습니다.</p><p class="path">{text(experiment.prereg?.sha256)}</p><div class="command"><code>{DATASET_COMMAND}</code><button onclick={()=>copy(DATASET_COMMAND)}>명령 복사</button></div><div class="command"><code>{TRAIN_COMMAND}</code><button onclick={()=>copy(TRAIN_COMMAND)}>명령 복사</button></div>{:else}<p>동결 전 · 연구 결과 주장 불가</p>{/if}{#if copyMessage}<p>{copyMessage}</p>{/if}</section>
<section class="card"><h2>계획된 실험 계약</h2><dl><div><dt>전략</dt><dd>{text(experiment.planned?.strategy)}</dd></div><div><dt>예측 구간</dt><dd>{text(experiment.planned?.horizons?.primary)}</dd></div><div><dt>seeds</dt><dd>{text(experiment.planned?.seeds)}</dd></div><div><dt>universe</dt><dd>{text(experiment.planned?.universe?.manifest)} · {text(experiment.planned?.universe?.size)}</dd></div></dl></section><section class="card boundary"><h2>실행 경계</h2><p>이 화면은 설계 열람용입니다. 학습 실행은 승인된 CLI로만 수행됩니다.</p></section></section>{/if}
<style>.experiment-page,.panel{width:100%;border:1px solid var(--border);border-radius:14px;padding:clamp(18px,4vw,32px);background:var(--surface);color:var(--fg)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(420px,1fr));gap:16px;margin-top:16px}.card{border:1px solid var(--border-strong);border-radius:10px;padding:16px;background:var(--surface-raised)}.wide{grid-column:1/-1;margin-top:16px}.eyebrow{margin:0;color:var(--accent);font-size:.82rem;font-weight:800;letter-spacing:.1em}h1{margin:7px 0;color:var(--fg-strong);font-size:clamp(1.8rem,6vw,2.6rem)}h2{color:var(--fg-strong);font-size:1.15rem}.stats p,dt{margin:0;color:var(--muted)}.stats strong{display:block;margin-top:8px;color:var(--fg-strong);font-size:1.3rem}.prereg,.boundary{margin-top:16px}.ready{border-color:var(--success);background:var(--success-soft)}.chip{border:1px solid currentColor;border-radius:999px;padding:2px 6px;color:var(--warn);font-size:.78rem}.ready .chip{color:var(--success)}.path,dd,code{overflow-wrap:anywhere}dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}dd{margin:3px 0 0}.command{display:flex;gap:10px;margin-top:10px}code{flex:1;border:1px solid var(--border-strong);border-radius:6px;padding:9px;font-size:.85rem}button{border:1px solid var(--accent);border-radius:6px;padding:6px 10px;background:transparent;color:var(--accent-strong);font:inherit}.error{color:var(--danger)}</style>