<script lang="ts">
  import { onMount } from 'svelte';
  import { getV6RunDetail, getV6Runs, type V6RunDetail, type V6Runs } from '../v6Api';
  let runsData = $state<V6Runs | null>(null); let error = $state<string | null>(null); let loading = $state(true); let selected = $state(''); let detail = $state<V6RunDetail | null>(null); let detailLoading = $state(false); let detailError = $state<string | null>(null);
  function display(value: unknown): string { return value === undefined || value === null || value === '' ? 'MISSING' : typeof value === 'string' ? value : JSON.stringify(value); }
  function shortSha(value: string | undefined): string { return value ? value.slice(0, 12) : 'MISSING'; }
  function won(value: unknown): string { return typeof value === 'number' ? `₩${new Intl.NumberFormat('ko-KR').format(value)}` : 'MISSING'; }
  function percent(value: unknown): string { return typeof value === 'number' ? `${value.toFixed(2)}%` : 'MISSING'; }
  function stateClass(state: string | undefined): string { return state === 'COMPLETED' || state === 'READY' ? 'complete' : state === 'RUNNING' || state === 'PARTIAL' ? 'running' : 'waiting'; }
  function runKey(dataset: string | undefined, run: string | undefined): string { return `${dataset ?? ''}\u0000${run ?? ''}`; }
  function events() { return detail?.events_tail?.slice(-10) ?? []; }
  async function load(): Promise<void> { loading = true; error = null; const result = await getV6Runs(); loading = false; if (result.ok && result.data) runsData = result.data; else error = result.error ?? '알 수 없는 오류가 발생했습니다.'; }
  async function expand(dataset: string | undefined, run: string | undefined): Promise<void> { if (!dataset || !run) return; const key = runKey(dataset, run); if (selected === key) { selected = ''; detail = null; detailError = null; return; } selected = key; detail = null; detailError = null; detailLoading = true; const result = await getV6RunDetail(dataset, run); detailLoading = false; if (result.ok && result.data) detail = result.data; else detailError = result.error ?? '실행 상세를 불러오지 못했습니다.'; }
  onMount(load);
</script>
{#if loading}<section class="panel" aria-live="polite">학습 실행 기록을 확인하고 있습니다.</section>
{:else if error}<section class="panel error" aria-live="assertive"><h1>학습 실행 기록을 불러오지 못했습니다</h1><p>{error}</p><button type="button" onclick={load}>다시 시도</button></section>
{:else if runsData}<section class="training-page" aria-labelledby="training-title"><header><p class="eyebrow">TRAINING LIFECYCLE</p><h1 id="training-title">학습</h1><p>실행 기록과 상세 manifest는 읽기 전용 API 응답에서만 표시합니다.</p></header>
{#if runsData.training_state === 'NOT_RUN'}<section class="empty-state"><h2>아직 어떤 V6 학습도 실행되지 않았습니다</h2><p>승인된 CLI로 학습이 실행되면 run UID, seed, episode, checkpoint, replay 증거가 이 화면에 나타납니다.</p></section>{/if}
<section class="card"><h2>데이터셋 실행 <span class="chip">{runsData.datasets?.length ?? 0}</span></h2>{#if runsData.datasets?.length}<div class="table-wrap"><table><thead><tr><th>run_id</th><th>generated_utc</th><th>split_row_counts</th><th>sha256</th></tr></thead><tbody>{#each runsData.datasets as dataset}<tr><td title={dataset.path}>{display(dataset.run_id)}</td><td>{display(dataset.generated_utc)}</td><td>{display(dataset.split_row_counts)}</td><td title={dataset.sha256}>{shortSha(dataset.sha256)}</td></tr>{/each}</tbody></table></div>{:else}<p class="absence">표시할 데이터셋 실행 기록이 없습니다.</p>{/if}</section>
<section class="card"><h2>학습 실행 <span class={`chip ${stateClass(runsData.training_state)}`}>{display(runsData.training_state)}</span></h2>{#if runsData.runs?.length}<div class="table-wrap"><table><thead><tr><th>run_id</th><th>state</th><th>seeds</th><th>generated_utc</th><th>상세</th></tr></thead><tbody>{#each runsData.runs as run}<tr><td title={run.path}>{display(run.run_id)}</td><td><span class={`chip ${stateClass(run.state)}`}>{display(run.state)}</span></td><td>{display(run.seeds)}</td><td>{display(run.generated_utc)}</td><td><button type="button" onclick={() => expand(run.dataset_run_id, run.run_id)}>{selected === runKey(run.dataset_run_id, run.run_id) ? '닫기' : '상세'}</button></td></tr>{/each}</tbody></table></div>{:else}<p class="absence">표시할 학습 실행 기록이 없습니다.</p>{/if}
{#if detailLoading}<p aria-live="polite">실행 상세를 읽고 있습니다.</p>{:else if detailError}<p class="detail-error" aria-live="assertive">실행 상세를 불러오지 못했습니다: {detailError}</p>{:else if detail?.reason}<p class="detail-error">{detail.reason}</p>{:else if detail?.manifest}<section class="detail"><h3>판정 <span class="verdict">{display(detail.manifest.verdict_candidate?.value)}</span></h3><div class="table-wrap"><table><thead><tr><th>seed</th><th>episodes_ran</th><th>best_episode</th><th>final val NAV</th><th>return</th><th>MDD</th><th>trades</th></tr></thead><tbody>{#each Object.entries(detail.manifest.per_seed ?? {}) as [seed, value]}<tr><th>{seed}</th><td>{display(value.episodes_ran)}</td><td>{display(value.best_episode)}</td><td>{won(value.final_val_metrics?.nav)}</td><td>{percent(value.final_val_metrics?.total_net_return_pct)}</td><td>{percent(value.final_val_metrics?.max_drawdown)}</td><td>{display(value.final_val_metrics?.trade_count)}</td></tr>{/each}</tbody></table></div><h3>최근 validation events</h3>{#if events().length}<ol>{#each events() as event}<li>episode {display(event.episode)} · val NAV {won(event.val_nav)}</li>{/each}</ol>{:else}<p class="absence">표시할 validation event가 없습니다.</p>{/if}</section>{/if}</section></section>{/if}
<style>.training-page,.panel{max-width:980px;border:1px solid var(--border);border-radius:14px;padding:clamp(18px,4vw,32px);background:var(--surface);color:var(--fg)}.eyebrow{color:var(--accent);font-size:.72rem;font-weight:800;letter-spacing:.1em}h1,h2,h3{color:var(--fg-strong)}header>p,.absence{color:var(--muted)}.card,.empty-state,.detail{margin-top:16px;border:1px solid var(--border-strong);border-radius:10px;padding:16px;background:var(--surface-raised)}.empty-state{border-color:var(--warn);background:var(--warn-soft)}.chip,.verdict{border:1px solid currentColor;border-radius:999px;padding:2px 6px;color:var(--warn);font-size:.68rem}.complete{color:var(--success)}.running{color:var(--info)}.verdict{color:var(--danger)}.table-wrap{max-width:100%;overflow-x:auto}table{width:100%;min-width:620px;border-collapse:collapse;font-size:.78rem}th,td{border-top:1px solid var(--border);padding:7px;text-align:left;overflow-wrap:anywhere}th{color:var(--muted)}button{border:1px solid var(--accent);border-radius:6px;padding:6px 10px;background:transparent;color:var(--accent-strong);font:inherit;cursor:pointer}.detail-error,.error{color:var(--danger)}</style>