<script lang="ts">
 import { onMount } from 'svelte'; import EChartsRenderer from '../../charts/EChartsRenderer.svelte'; import { getV6RunDetail,getV6Runs,type V6RunDetail,type V6Runs } from '../v6Api';
 let runsData=$state<V6Runs|null>(null);let error=$state<string|null>(null);let loading=$state(true);let selected=$state('');let detail=$state<V6RunDetail|null>(null);let detailLoading=$state(false);let detailError=$state<string|null>(null);
 const text=(v:unknown)=>v===undefined||v===null||v===''?'MISSING':String(v);const won=(v:unknown)=>typeof v==='number'?`₩${new Intl.NumberFormat('ko-KR').format(v)}`:'MISSING'; const key=(d:string|undefined,r:string|undefined)=>`${d??''}\u0000${r??''}`; const color=(name:string)=>typeof document==='undefined'?'transparent':getComputedStyle(document.documentElement).getPropertyValue(name).trim();
 const events=$derived((detail?.events_tail??[]).filter((e)=>typeof e.episode==='number'&&typeof e.val_nav==='number'));
 const navOption=$derived({tooltip:{trigger:'axis',valueFormatter:(v:number)=>won(v)},xAxis:{type:'category',name:'episode',data:events.map(e=>e.episode)},yAxis:{type:'value',axisLabel:{formatter:(v:number)=>won(v)}},series:[{type:'line',data:events.map(e=>e.val_nav),smooth:false,itemStyle:{color:color('--accent')},markLine:{silent:true,data:[{yAxis:60000000,label:{formatter:'no-trade 60M'}}]}}]});
 async function open(d:string|undefined,r:string|undefined){if(!d||!r)return;selected=key(d,r);detail=null;detailError=null;detailLoading=true;const x=await getV6RunDetail(d,r);detailLoading=false;if(x.ok&&x.data)detail=x.data;else detailError=x.error??'실행 상세를 불러오지 못했습니다.'} async function load(){loading=true;error=null;const x=await getV6Runs();loading=false;if(x.ok&&x.data){runsData=x.data;const run=x.data.runs?.[0];if(run)open(run.dataset_run_id,run.run_id)}else error=x.error??'알 수 없는 오류가 발생했습니다.'} onMount(load);
</script>
{#if loading}<section class="panel">학습 실행 기록을 확인하고 있습니다.</section>{:else if error}<section class="panel error"><h1>학습 실행 기록을 불러오지 못했습니다</h1><p>{error}</p></section>{:else if runsData}<section class="training-page"><header><p class="eyebrow">TRAINING LIFECYCLE</p><h1>학습</h1><p>실행 기록과 상세 manifest는 읽기 전용 API 응답에서만 표시합니다.</p></header>{#if runsData.training_state==='NOT_RUN'}<section class="empty-state"><h2>아직 어떤 V6 학습도 실행되지 않았습니다</h2><p>승인된 CLI로 학습이 실행되면 증거가 이 화면에 나타납니다.</p></section>{/if}
<div class="grid"><section class="card"><h2>데이터셋 실행</h2><div class="table-wrap"><table><thead><tr><th>run_id</th><th>generated_utc</th><th>sha256</th></tr></thead><tbody>{#each runsData.datasets??[] as d}<tr><td>{text(d.run_id)}</td><td>{text(d.generated_utc)}</td><td title={d.sha256}>{text(d.sha256).slice(0,12)}</td></tr>{:else}<tr><td colspan="3">표시할 데이터 없음 · NOT_RUN</td></tr>{/each}</tbody></table></div></section><section class="card"><h2>학습 실행</h2><div class="table-wrap"><table><thead><tr><th>run_id</th><th>state</th><th>상세</th></tr></thead><tbody>{#each runsData.runs??[] as run}<tr><td>{text(run.run_id)}</td><td>{text(run.state)}</td><td><button onclick={()=>open(run.dataset_run_id,run.run_id)}>{selected===key(run.dataset_run_id,run.run_id)?'선택됨':'상세'}</button></td></tr>{:else}<tr><td colspan="3">표시할 데이터 없음 · NOT_RUN</td></tr>{/each}</tbody></table></div></section></div>
{#if detailLoading}<section class="card wide">실행 상세를 읽고 있습니다.</section>{:else if detailError}<section class="card error">{detailError}</section>{:else if detail?.manifest}<section class="card wide"><h2>선택 실행 validation NAV</h2>{#if events.length}<EChartsRenderer option={navOption} height="320px" caption="episode별 validation NAV · no-trade 60M" />{:else}<p class="absence">표시할 데이터 없음 · NOT_RUN</p>{/if}</section><div class="grid"><section class="card"><h2>seed별 검증</h2><div class="table-wrap"><table><thead><tr><th>seed</th><th>episodes</th><th>final val NAV</th></tr></thead><tbody>{#each Object.entries(detail.manifest.per_seed??{}) as [seed,value]}<tr><th>{seed}</th><td>{text(value.episodes_ran)}</td><td>{won(value.final_val_metrics?.nav)}</td></tr>{/each}</tbody></table></div></section><section class="card"><h2>판정</h2><p>{text(detail.manifest.verdict_candidate?.value)}</p></section></div>{/if}</section>{/if}
<style>.training-page,.panel{width:100%;border:1px solid var(--border);border-radius:14px;padding:clamp(18px,4vw,32px);background:var(--surface);color:var(--fg)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(420px,1fr));gap:16px;margin-top:16px}.card,.empty-state{border:1px solid var(--border-strong);border-radius:10px;padding:16px;background:var(--surface-raised)}.wide{grid-column:1/-1;margin-top:16px}.empty-state{margin-top:16px;border-color:var(--warn);background:var(--warn-soft)}.eyebrow{color:var(--accent);font-size:.82rem;font-weight:800;letter-spacing:.1em}h1{color:var(--fg-strong);font-size:clamp(1.8rem,6vw,2.6rem)}h2{color:var(--fg-strong);font-size:1.15rem}.absence{color:var(--muted)}.table-wrap{overflow-x:auto}table{width:100%;min-width:420px;border-collapse:collapse;font-size:.85rem}th,td{border-top:1px solid var(--border);padding:8px;text-align:left}th{color:var(--muted)}button{border:1px solid var(--accent);border-radius:6px;padding:6px 10px;background:transparent;color:var(--accent-strong);font:inherit}.error{color:var(--danger)}</style>